-- Migration 001: Initial schema for trading system database
-- Description: Creates tables for trades, signals, performance snapshots, and parameter history
-- Author: Trading System
-- Date: 2025-10-10

-- Table: trades
-- Stores all trade execution records with full P&L tracking
CREATE TABLE IF NOT EXISTS trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trade_id VARCHAR(255) UNIQUE NOT NULL,
    signal_id VARCHAR(255),
    account_id VARCHAR(255) NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('BUY', 'SELL')),
    entry_time TIMESTAMP NOT NULL,
    entry_price DECIMAL(10, 5) NOT NULL,
    exit_time TIMESTAMP,
    exit_price DECIMAL(10, 5),
    stop_loss DECIMAL(10, 5),
    take_profit DECIMAL(10, 5),
    position_size DECIMAL(15, 2) NOT NULL,
    pnl DECIMAL(10, 2),
    pnl_percentage DECIMAL(5, 2),
    session VARCHAR(20) CHECK (session IN ('TOKYO', 'LONDON', 'NY', 'SYDNEY', 'OVERLAP') OR session IS NULL),
    pattern_type VARCHAR(100),
    confidence_score DECIMAL(5, 2),
    risk_reward_ratio DECIMAL(4, 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: signals
-- Tracks all signals generated by the market analysis agent
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id VARCHAR(255) UNIQUE NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    timeframe VARCHAR(20),
    signal_type VARCHAR(10) NOT NULL CHECK (signal_type IN ('BUY', 'SELL')),
    confidence DECIMAL(5, 2) NOT NULL,
    entry_price DECIMAL(10, 5),
    stop_loss DECIMAL(10, 5),
    take_profit DECIMAL(10, 5),
    session VARCHAR(20) CHECK (session IN ('TOKYO', 'LONDON', 'NY', 'SYDNEY', 'OVERLAP') OR session IS NULL),
    pattern_type VARCHAR(100),
    generated_at TIMESTAMP NOT NULL,
    executed BOOLEAN NOT NULL DEFAULT 0,
    execution_status VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: performance_snapshots
-- Captures system performance metrics at regular intervals
CREATE TABLE IF NOT EXISTS performance_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_time TIMESTAMP NOT NULL,
    total_trades INTEGER NOT NULL DEFAULT 0,
    winning_trades INTEGER NOT NULL DEFAULT 0,
    losing_trades INTEGER NOT NULL DEFAULT 0,
    win_rate DECIMAL(5, 2) NOT NULL DEFAULT 0.0,
    total_pnl DECIMAL(15, 2) NOT NULL DEFAULT 0.0,
    sharpe_ratio DECIMAL(6, 3),
    max_drawdown DECIMAL(5, 2),
    average_rr DECIMAL(4, 2),
    session VARCHAR(20) CHECK (session IN ('TOKYO', 'LONDON', 'NY', 'SYDNEY', 'OVERLAP') OR session IS NULL),
    parameter_mode VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: parameter_history
-- Tracks all changes to trading parameters
CREATE TABLE IF NOT EXISTS parameter_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    change_time TIMESTAMP NOT NULL,
    parameter_mode VARCHAR(50) NOT NULL,
    session VARCHAR(20) CHECK (session IN ('TOKYO', 'LONDON', 'NY', 'SYDNEY', 'OVERLAP') OR session IS NULL),
    confidence_threshold DECIMAL(5, 2),
    min_risk_reward DECIMAL(4, 2),
    reason TEXT,
    changed_by VARCHAR(50) NOT NULL CHECK (changed_by IN ('system_auto', 'learning_agent', 'manual', 'emergency')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_trades_symbol_time ON trades(symbol, entry_time);
CREATE INDEX IF NOT EXISTS idx_trades_session ON trades(session);
CREATE INDEX IF NOT EXISTS idx_trades_pattern ON trades(pattern_type);
CREATE INDEX IF NOT EXISTS idx_trades_trade_id ON trades(trade_id);

CREATE INDEX IF NOT EXISTS idx_signals_generated_at ON signals(generated_at);
CREATE INDEX IF NOT EXISTS idx_signals_signal_id ON signals(signal_id);

CREATE INDEX IF NOT EXISTS idx_snapshots_time ON performance_snapshots(snapshot_time);
