# Prometheus Alert Rules for Trading Management System
# Critical alerts for financial system safety and operational monitoring

groups:
  - name: system.critical
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
          category: availability
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 30 seconds."
          runbook_url: "https://docs.trading-system.local/runbooks/service-down"

      # Circuit breaker critical alerts
      - alert: CircuitBreakerSystemOpen
        expr: agent_circuit_breaker_state{breaker_tier="system"} == 2
        for: 0s  # Immediate alert
        labels:
          severity: critical
          category: safety
          tier: system
        annotations:
          summary: "SYSTEM-LEVEL CIRCUIT BREAKER ACTIVATED - ALL TRADING HALTED"
          description: "System-level circuit breaker for {{ $labels.agent_type }} is OPEN. All trading operations are halted."
          action: "IMMEDIATE: Check system health, review recent trades, contact operations team"

      - alert: CircuitBreakerAccountOpen
        expr: agent_circuit_breaker_state{breaker_tier="account"} == 2
        for: 0s
        labels:
          severity: critical
          category: safety
          tier: account
        annotations:
          summary: "Account-level circuit breaker activated for {{ $labels.agent_type }}"
          description: "Account-level circuit breaker is OPEN - trading halted for specific accounts."

      # Extreme latency alerts (financial system critical)
      - alert: HighLatencyExecutionCritical
        expr: histogram_quantile(0.95, rate(agent_message_processing_duration_seconds_bucket{message_type="trade_execution"}[1m])) > 0.5
        for: 10s
        labels:
          severity: critical
          category: performance
        annotations:
          summary: "CRITICAL: Trade execution latency >500ms"
          description: "95th percentile execution latency is {{ $value }}s for {{ $labels.agent_type }}"
          action: "Check execution engine, network, and broker connections immediately"

  - name: system.high
    rules:
      # Resource utilization alerts
      - alert: HighCPUUsage
        expr: system_cpu_usage_percent > 80
        for: 2m
        labels:
          severity: high
          category: resources
        annotations:
          summary: "High CPU usage on {{ $labels.service }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.service }}"

      - alert: HighMemoryUsage
        expr: (system_memory_usage_bytes{memory_type="used"} / (system_memory_usage_bytes{memory_type="used"} + system_memory_usage_bytes{memory_type="available"})) * 100 > 70
        for: 2m
        labels:
          severity: high
          category: resources
        annotations:
          summary: "High memory usage on {{ $labels.service }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.service }}"

      - alert: HighDiskUsage
        expr: (system_disk_usage_bytes{disk_type="used"} / (system_disk_usage_bytes{disk_type="used"} + system_disk_usage_bytes{disk_type="free"})) * 100 > 85
        for: 5m
        labels:
          severity: high
          category: resources
        annotations:
          summary: "High disk usage on {{ $labels.service }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.service }} at {{ $labels.mountpoint }}"

      # Agent communication latency
      - alert: HighInterAgentLatency
        expr: histogram_quantile(0.95, rate(agent_inter_agent_latency_seconds_bucket[2m])) > 0.01
        for: 1m
        labels:
          severity: high
          category: performance
        annotations:
          summary: "High latency between agents"
          description: "95th percentile inter-agent latency is {{ $value }}s between {{ $labels.source_agent }} and {{ $labels.destination_agent }}"

  - name: trading.business
    rules:
      # Trading performance alerts
      - alert: LowTradingSuccessRate
        expr: trading_success_rate < 60
        for: 5m
        labels:
          severity: medium
          category: trading_performance
        annotations:
          summary: "Low trading success rate for {{ $labels.agent_type }}"
          description: "Success rate is {{ $value }}% for {{ $labels.agent_type }} on {{ $labels.account_id }}"

      - alert: HighDrawdown
        expr: trading_drawdown_current_percent > 15
        for: 1m
        labels:
          severity: high
          category: risk_management
        annotations:
          summary: "High drawdown detected on {{ $labels.account_id }}"
          description: "Current drawdown is {{ $value }}% on account {{ $labels.account_id }}"
          action: "Review position sizes and risk parameters immediately"

      # Signal generation alerts
      - alert: LowSignalGeneration
        expr: rate(trading_signals_generated_total[5m]) < 0.1
        for: 10m
        labels:
          severity: medium
          category: signal_generation
        annotations:
          summary: "Low signal generation rate for {{ $labels.agent_type }}"
          description: "Signal generation rate has dropped to {{ $value }} signals/second"

      # Risk calculation performance
      - alert: SlowRiskCalculation
        expr: histogram_quantile(0.95, rate(trading_risk_calculation_duration_seconds_bucket[2m])) > 1.0
        for: 2m
        labels:
          severity: medium
          category: risk_performance
        annotations:
          summary: "Slow risk calculations detected"
          description: "95th percentile risk calculation time is {{ $value }}s for {{ $labels.agent_type }}"

  - name: infrastructure.alerts
    rules:
      # Database alerts
      - alert: DatabaseConnectionsHigh
        expr: database_connections_active > 80
        for: 2m
        labels:
          severity: medium
          category: database
        annotations:
          summary: "High database connections for {{ $labels.service }}"
          description: "Active connections: {{ $value }} for {{ $labels.database }}"

      - alert: SlowDatabaseQueries
        expr: histogram_quantile(0.95, rate(database_query_duration_seconds_bucket[2m])) > 2.0
        for: 1m
        labels:
          severity: medium
          category: database
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile query time is {{ $value }}s for {{ $labels.operation }} on {{ $labels.database }}"

      # Kafka alerts
      - alert: KafkaConsumerLag
        expr: kafka_consumer_lag_messages > 1000
        for: 2m
        labels:
          severity: medium
          category: messaging
        annotations:
          summary: "High Kafka consumer lag"
          description: "Consumer lag is {{ $value }} messages for {{ $labels.topic }} partition {{ $labels.partition }}"

  - name: security.alerts
    rules:
      # Authentication failures
      - alert: HighAuthenticationFailures
        expr: increase(security_authentication_failures_total[5m]) > 10
        for: 1m
        labels:
          severity: high
          category: security
        annotations:
          summary: "High authentication failure rate"
          description: "{{ $value }} authentication failures in the last 5 minutes"
          action: "Check for brute force attacks or credential issues"

      # Unauthorized access attempts
      - alert: UnauthorizedAccessAttempts
        expr: increase(security_unauthorized_access_total[5m]) > 5
        for: 30s
        labels:
          severity: critical
          category: security
        annotations:
          summary: "Unauthorized access attempts detected"
          description: "{{ $value }} unauthorized access attempts in the last 5 minutes"
          action: "IMMEDIATE: Review access logs and consider blocking source IPs"