apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-integration
  namespace: tmt-production
  labels:
    app: broker-integration
    component: agent
    version: v1
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: broker-integration
  template:
    metadata:
      labels:
        app: broker-integration
        component: agent
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: broker-integration-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: broker-service
        image: tmt/broker-integration:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: broker-integration-config
              key: vault_addr
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: broker-integration-secrets
              key: vault_token
        - name: PROMETHEUS_PORT
          value: "9090"
        - name: HEALTH_CHECK_PORT
          value: "8000"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: data
          mountPath: /app/data
        - name: temp-retention
          mountPath: /app/temp_retention
        - name: transaction-data
          mountPath: /app/transaction_data
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: logs
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: broker-integration-data
      - name: temp-retention
        persistentVolumeClaim:
          claimName: broker-integration-temp
      - name: transaction-data
        persistentVolumeClaim:
          claimName: broker-integration-transactions
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: "tmt.com/broker-integration"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - broker-integration
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker-integration-sa
  namespace: tmt-production
  labels:
    app: broker-integration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-integration-config
  namespace: tmt-production
  labels:
    app: broker-integration
data:
  vault_addr: "https://vault.tmt.internal:8200"
  log_level: "INFO"
  prometheus_port: "9090"
  pool_size: "20"
  max_retries: "10"
  reconnection_timeout: "5.0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-integration-data
  namespace: tmt-production
  labels:
    app: broker-integration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-integration-temp
  namespace: tmt-production
  labels:
    app: broker-integration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-integration-transactions
  namespace: tmt-production
  labels:
    app: broker-integration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd