# Prometheus Configuration for TMT Trading System Monitoring
# Monitors critical performance and reliability metrics for production deployment

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules configuration
rule_files:
  - "alert_rules.yml"
  - "latency_rules.yml"
  - "uptime_rules.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configuration for TMT system components
scrape_configs:
  # Main trading application metrics
  - job_name: 'tmt-trading-system'
    static_configs:
      - targets: ['localhost:8000']  # FastAPI main service
    metrics_path: '/metrics'
    scrape_interval: 5s  # High frequency for trading system
    scrape_timeout: 3s

  # Circuit Breaker Agent metrics
  - job_name: 'circuit-breaker-agent'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    
  # Compliance Agent metrics  
  - job_name: 'compliance-agent'
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Wyckoff Analysis Agent metrics
  - job_name: 'wyckoff-agent'
    static_configs:
      - targets: ['localhost:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # ARIA Risk Agent metrics
  - job_name: 'aria-risk-agent'
    static_configs:
      - targets: ['localhost:8004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Execution Engine metrics
  - job_name: 'execution-engine'
    static_configs:
      - targets: ['localhost:8005']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Anti-Correlation Agent metrics
  - job_name: 'anti-correlation-agent'
    static_configs:
      - targets: ['localhost:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Human Behavior Agent metrics
  - job_name: 'human-behavior-agent'
    static_configs:
      - targets: ['localhost:8007']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Continuous Improvement Agent metrics
  - job_name: 'continuous-improvement-agent'
    static_configs:
      - targets: ['localhost:8008']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Database metrics (PostgreSQL + TimescaleDB)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 15s

  # Message Queue metrics (Kafka/NATS)
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['localhost:9308']
    scrape_interval: 15s

  # System metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # MetaTrader Bridge metrics
  - job_name: 'mt-bridge'
    static_configs:
      - targets: ['localhost:8010']
    metrics_path: '/metrics'
    scrape_interval: 5s

# Custom metric relabeling for trading-specific metrics
metric_relabel_configs:
  # Signal-to-execution latency tracking
  - source_labels: [__name__]
    regex: 'tmt_signal_execution_duration_seconds'
    target_label: critical_metric
    replacement: 'latency'

  # Uptime tracking
  - source_labels: [__name__]
    regex: 'up'
    target_label: critical_metric
    replacement: 'availability'

  # Trade execution success rate
  - source_labels: [__name__]
    regex: 'tmt_trade_execution_success_rate'
    target_label: critical_metric
    replacement: 'reliability'