apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "GET"
      manageAlerts: true
      prometheusType: "Prometheus"
      prometheusVersion: "2.49.1"
      cacheLevel: "High"
      disableMetricsLookup: false
      incrementalQuerying: false
      exemplarTraceIdDestinations:
        - name: "Jaeger"
          datasourceUid: "jaeger_ds"
          urlDisplayLabel: "View in Jaeger"

  - name: Jaeger
    type: jaeger
    uid: jaeger_ds
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki_ds'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: ['correlation_id', 'service_name']
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{service="${__data.fields.serviceName}"} |= "${__data.fields.traceId}"'
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: '1h' 
        spanEndTimeShift: '-1h'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'operation' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'

  - name: Loki
    type: loki
    uid: loki_ds
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - matcherRegex: "correlation_id=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"
          datasourceUid: "jaeger_ds"